title: Tanvir Bhupal
description: Practical real estate guidance for families moving to Fleetwood, Tynehead, and Fraser Heights.
url: "https://gvancouverhomes.com"
baseurl: "/tanvirbhupal-website"

author:
  name: Tanvir Bhupal

markdown: kramdown
permalink: pretty

exclude:
  - README.md
